# COURSE OUTLINE

# GET INFORMATION ABOUT THE BUSINESS OR THE ORGANIZATION
# KNOW THE PROBLEM AT HAND
# GETTING THE RIGHT DATA
# EDA EXPLORATORY DATA ANALYSIS
    # DATA CLEANING
    # DATA TRANSFORMATION
    # DESCRIPTIVE DATA ANALYSIS USING (PYTHON, POWERBI, TABLEAU)
    # DATA VISUALIZATION (PYTHON, POWERBI, TABLEAU)
    # MACHINE LEANRING (PYTHON) (LINEAR REGRESSION, BINARY CLASSIFICATION, MULTCLASSIFICATION, CLUSTERING, TEXT OR SENTIMENT ANALYSIS)
    # PREPROCESSING
    # MODEL BUILDING
    # EVALUATION (VERIFICATION)
    # MODEL DEPLOYMENT
# DEEP LEARNING

In [2]:
# NUMPY : NUMERICAL PYTHON
import numpy as np
arr1 = np.array([78,88,56,87,43])
arr1

array([78, 88, 56, 87, 43])

In [3]:
arr1.ndim # checking the numbers of array dimension

1

In [4]:
arr1.shape # checking the shape of the array. it could be two dimensional as a matrix or one dimensional

(5,)

In [5]:
arr1.dtype # checking the data type of the array

dtype('int32')

In [6]:
arr2 = np.array([[34,56,23,66,76], [65,77,65,34,21]])
arr2

array([[34, 56, 23, 66, 76],
       [65, 77, 65, 34, 21]])

In [7]:
arr2.ndim # this tells us that the array is two dimensional

2

In [8]:
arr2.dtype

dtype('int32')

In [9]:
arr2.shape

(2, 5)

In [10]:
# creating an array where all values are zero
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [11]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# creating an array where all values are one
np.ones(80)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
np.ones((6,6)) * 15

array([[15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15.]])

In [15]:
# LIN SPACE: lin space generates arrays that are evenly spaced over an interval. over a specified interval. the interval must be set
np.linspace(30,90)

array([30.        , 31.2244898 , 32.44897959, 33.67346939, 34.89795918,
       36.12244898, 37.34693878, 38.57142857, 39.79591837, 41.02040816,
       42.24489796, 43.46938776, 44.69387755, 45.91836735, 47.14285714,
       48.36734694, 49.59183673, 50.81632653, 52.04081633, 53.26530612,
       54.48979592, 55.71428571, 56.93877551, 58.16326531, 59.3877551 ,
       60.6122449 , 61.83673469, 63.06122449, 64.28571429, 65.51020408,
       66.73469388, 67.95918367, 69.18367347, 70.40816327, 71.63265306,
       72.85714286, 74.08163265, 75.30612245, 76.53061224, 77.75510204,
       78.97959184, 80.20408163, 81.42857143, 82.65306122, 83.87755102,
       85.10204082, 86.32653061, 87.55102041, 88.7755102 , 90.        ])

In [17]:
np.eye(9) # the eye will create a 2D array having zero elsewhere and one on the diagonal

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# ARRAY RANGE (ARANGE)

In [21]:
arr4 = np.arange(1,101) # arrange numbers in a array
arr4

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [25]:
arr51 = np.arange(1,101,2.5) # arranges the array according to a specified interval
arr5

array([ 1. ,  3.5,  6. ,  8.5, 11. , 13.5, 16. , 18.5, 21. , 23.5, 26. ,
       28.5, 31. , 33.5, 36. , 38.5, 41. , 43.5, 46. , 48.5, 51. , 53.5,
       56. , 58.5, 61. , 63.5, 66. , 68.5, 71. , 73.5, 76. , 78.5, 81. ,
       83.5, 86. , 88.5, 91. , 93.5, 96. , 98.5])

In [31]:
arr5 = np.random.randint(15,105,100)
arr5

array([ 69,  60,  61,  51,  37,  94,  71,  32,  92,  57,  94,  32,  80,
        28,  89,  60,  65,  46,  22,  70,  62,  90,  33,  55,  35,  49,
        95,  44,  53, 104,  29,  88,  23,  49,  59,  93,  26,  73,  62,
        91,  70,  60,  86,  16,  96,  48,  31,  72,  78,  85,  41,  88,
        43,  46,  44,  32,  59,  45,  60,  91,  76,  94,  48,  84,  46,
        95,  99,  58,  37,  18,  81,  76,  47,  89,  97,  94,  90,  21,
        94,  77,  51,  35,  70,  51,  67,  51,  40,  90,  25,  83,  44,
        77,  52,  72, 101,  74,  58,  28,  16,  15])

In [32]:
np.random.seed(5) # this is done to have a unique set of random arrays
arr5 = np.random.randint(15,105,100)
arr5

array([ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22,  91,  30,  68,
        95,  42,  59,  92,  90,  80,  62,  45,  99, 101,  33,  24,  56,
        77,  16,  97,  31,  93,  20,  73,  15,  95,  19,  51,  66,  42,
        46,  17,  83,  53,  98,  34,  33,  22,  45,  77,  26,  82,  80,
        70,  18,  93,  42,  44,  48, 104, 100,  22,  31,  29,  46,  24,
        53,  62,  31,  20,  49,  60,  74,  39,  28,  46,  47,  91,  59,
        20,  29,  62,  97,  15,  22, 101,  31,  79,  23,  59,  52,  90,
        20,  37,  67,  84,  97,  75,  44, 103,  94])

# conversion of 1D array to 2D array

In [33]:
arr6 = arr5.reshape((10,10))

In [34]:
arr6

array([[ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22],
       [ 91,  30,  68,  95,  42,  59,  92,  90,  80,  62],
       [ 45,  99, 101,  33,  24,  56,  77,  16,  97,  31],
       [ 93,  20,  73,  15,  95,  19,  51,  66,  42,  46],
       [ 17,  83,  53,  98,  34,  33,  22,  45,  77,  26],
       [ 82,  80,  70,  18,  93,  42,  44,  48, 104, 100],
       [ 22,  31,  29,  46,  24,  53,  62,  31,  20,  49],
       [ 60,  74,  39,  28,  46,  47,  91,  59,  20,  29],
       [ 62,  97,  15,  22, 101,  31,  79,  23,  59,  52],
       [ 90,  20,  37,  67,  84,  97,  75,  44, 103,  94]])

In [35]:
arr5 = arr6.reshape(100)

In [36]:
arr5

array([ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22,  91,  30,  68,
        95,  42,  59,  92,  90,  80,  62,  45,  99, 101,  33,  24,  56,
        77,  16,  97,  31,  93,  20,  73,  15,  95,  19,  51,  66,  42,
        46,  17,  83,  53,  98,  34,  33,  22,  45,  77,  26,  82,  80,
        70,  18,  93,  42,  44,  48, 104, 100,  22,  31,  29,  46,  24,
        53,  62,  31,  20,  49,  60,  74,  39,  28,  46,  47,  91,  59,
        20,  29,  62,  97,  15,  22, 101,  31,  79,  23,  59,  52,  90,
        20,  37,  67,  84,  97,  75,  44, 103,  94])

In [37]:
# calling a number from a 2D array
arr6[4,5]

33

In [38]:
# selecting more than one value in a 2D array
arr6[3:7,5:9] # row 3 to row 6 and column 5 to column 8

array([[ 19,  51,  66,  42],
       [ 33,  22,  45,  77],
       [ 42,  44,  48, 104],
       [ 53,  62,  31,  20]])

In [41]:
# BROADCASTING A VALUE TO THE 2D ARRAY
arr6[2:7,3:8] = 100
arr6

array([[ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22],
       [ 91,  30,  68,  95,  42,  59,  92,  90,  80,  62],
       [ 45,  99, 101, 100, 100, 100, 100, 100,  97,  31],
       [ 93,  20,  73, 100, 100, 100, 100, 100,  42,  46],
       [ 17,  83,  53, 100, 100, 100, 100, 100,  77,  26],
       [ 82,  80,  70, 100, 100, 100, 100, 100, 104, 100],
       [ 22,  31,  29, 100, 100, 100, 100, 100,  20,  49],
       [ 60,  74,  39,  28,  46,  47,  91,  59,  20,  29],
       [ 62,  97,  15,  22, 101,  31,  79,  23,  59,  52],
       [ 90,  20,  37,  67,  84,  97,  75,  44, 103,  94]])

In [42]:
arr7 = arr6.flatten()

In [43]:
arr7

array([ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22,  91,  30,  68,
        95,  42,  59,  92,  90,  80,  62,  45,  99, 101, 100, 100, 100,
       100, 100,  97,  31,  93,  20,  73, 100, 100, 100, 100, 100,  42,
        46,  17,  83,  53, 100, 100, 100, 100, 100,  77,  26,  82,  80,
        70, 100, 100, 100, 100, 100, 104, 100,  22,  31,  29, 100, 100,
       100, 100, 100,  20,  49,  60,  74,  39,  28,  46,  47,  91,  59,
        20,  29,  62,  97,  15,  22, 101,  31,  79,  23,  59,  52,  90,
        20,  37,  67,  84,  97,  75,  44, 103,  94])

In [44]:
np.sum(arr7)

7036

In [46]:
np.mean(arr7)

70.36

In [47]:
np.std(arr7)

29.750132772812965

In [48]:
np.var(arr7)

885.0704

In [49]:
np.max(arr7)

104

In [50]:
np.min(arr7)

15

In [51]:
np.median(arr7)

79.5

In [52]:
np.cos(arr7)

array([ 0.3174287 ,  0.82433133,  0.91474236,  0.99937328, -0.53283302,
       -0.03097503, -0.39998531,  0.52532199,  0.73017356, -0.99996083,
       -0.99436746,  0.15425145,  0.44014302,  0.73017356, -0.39998531,
       -0.77108022, -0.62644445, -0.44807362, -0.11038724,  0.67350716,
        0.52532199,  0.03982088,  0.89200487,  0.86231887,  0.86231887,
        0.86231887,  0.86231887,  0.86231887, -0.92514754,  0.91474236,
        0.3174287 ,  0.40808206, -0.73619272,  0.86231887,  0.86231887,
        0.86231887,  0.86231887,  0.86231887, -0.39998531, -0.43217794,
       -0.27516334,  0.24954012, -0.91828279,  0.86231887,  0.86231887,
        0.86231887,  0.86231887,  0.86231887, -0.03097503,  0.64691932,
        0.9496777 , -0.11038724,  0.6333192 ,  0.86231887,  0.86231887,
        0.86231887,  0.86231887,  0.86231887, -0.94686801,  0.86231887,
       -0.99996083,  0.91474236, -0.74805753,  0.86231887,  0.86231887,
        0.86231887,  0.86231887,  0.86231887,  0.40808206,  0.30

In [53]:
np.square(arr7)

array([ 8649,  5776,   961,  7744,   529,  5929,  1764,  2025,  9025,
         484,  8281,   900,  4624,  9025,  1764,  3481,  8464,  8100,
        6400,  3844,  2025,  9801, 10201, 10000, 10000, 10000, 10000,
       10000,  9409,   961,  8649,   400,  5329, 10000, 10000, 10000,
       10000, 10000,  1764,  2116,   289,  6889,  2809, 10000, 10000,
       10000, 10000, 10000,  5929,   676,  6724,  6400,  4900, 10000,
       10000, 10000, 10000, 10000, 10816, 10000,   484,   961,   841,
       10000, 10000, 10000, 10000, 10000,   400,  2401,  3600,  5476,
        1521,   784,  2116,  2209,  8281,  3481,   400,   841,  3844,
        9409,   225,   484, 10201,   961,  6241,   529,  3481,  2704,
        8100,   400,  1369,  4489,  7056,  9409,  5625,  1936, 10609,
        8836])

In [54]:
np.sqrt(arr7)

array([ 9.64365076,  8.71779789,  5.56776436,  9.38083152,  4.79583152,
        8.77496439,  6.4807407 ,  6.70820393,  9.74679434,  4.69041576,
        9.53939201,  5.47722558,  8.24621125,  9.74679434,  6.4807407 ,
        7.68114575,  9.59166305,  9.48683298,  8.94427191,  7.87400787,
        6.70820393,  9.94987437, 10.04987562, 10.        , 10.        ,
       10.        , 10.        , 10.        ,  9.8488578 ,  5.56776436,
        9.64365076,  4.47213595,  8.54400375, 10.        , 10.        ,
       10.        , 10.        , 10.        ,  6.4807407 ,  6.78232998,
        4.12310563,  9.11043358,  7.28010989, 10.        , 10.        ,
       10.        , 10.        , 10.        ,  8.77496439,  5.09901951,
        9.05538514,  8.94427191,  8.36660027, 10.        , 10.        ,
       10.        , 10.        , 10.        , 10.19803903, 10.        ,
        4.69041576,  5.56776436,  5.38516481, 10.        , 10.        ,
       10.        , 10.        , 10.        ,  4.47213595,  7.  

In [55]:
np.percentile(arr7,50)

79.5

In [56]:
np.argmax(arr7) # the position of the first highest value which is 104

58

In [57]:
np.argmin(arr7)  # the position of the first lowest value which is 104

82

# important read-ups

In [ ]:
# 1. DOMAIN KNOWLEDGE
# 2. COMMUNICATION SKILL
# 3. PROBLEM SOLVING AND ERICTICAL THINKING
# 4. COLLABORATION AND TEAM WORK
# 5. ETHICS AND DATA PRIVACY
# 6. PROJECT MANAGEMENT
# 7. BUSINESS ACUMEN
# 8. ADPATABILITY AND CONTIONOUR LEARNING
# 9. THE ART OF COMMUNICATION
# 10. TAILORING CPMMUNICATION TO YOUR AUDIENCE
# 11. PERSUASIVE COMMUNICATION
# 12. MASTERING VIDUALIZATION TOOLS
# 13. CHOOSING THE RIGHT VISUALS
# 14. DESIGN PRINCIPLES
# 15. DATA STORYTELLING AND CONTEXT
# 16. EMOTIONAL INTELLIGENCE IN COMMUNICATION
# 17. VISUAL STORYTELLING
# 18. USING DASHBOARD EFFECTIVELY
# 19. 